version: "2"

run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  default: all
  exclusions:
    paths:
      - "transport/event/.*_gen_test\\.go$"
    rules:
      - path: _test\.go
        linters:
          - funlen
          - dupl
      - path: ^transport/event/.*_gen_test\.go$
        linters:
          - errcheck
        text: "Error return value of .* is not checked"
      - path: .*
        linters:
          - gci
          - gofumpt
          - exhaustivestruct
          - exhaustruct
          - wrapcheck
          - tagliatelle
          - dupl
          - varnamelen
          - nonamedreturns
          - funlen
          - depguard
