name: Lint & test & build

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  DO_PUSH: ${{ github.ref == 'refs/heads/main' }}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache: false

      - name: Generate
        run: |-
          go get -u -t github.com/tinylib/msgp
          go install github.com/tinylib/msgp
          make gen

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
          working-directory: .
          version: v1.62.2
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache: false

      - name: Generate
        run: |-
          go get -u -t github.com/tinylib/msgp
          go install github.com/tinylib/msgp
          make gen

      - name: Test
        run: make test
        env:
          CFG_PATH: ./conf/config.github.json
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: ${{ env.DO_PUSH == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        if: ${{ env.DO_PUSH == 'false' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/swup:pass-0.0.12
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/swup:pass-latest

      - name: Build and push
        if: ${{ env.DO_PUSH == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/swup:pass-0.0.12
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/swup:pass-latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/swup:pass-latest,mode=max
